(defpackage #:llama
  (:use #:cl)
  (:export "*THREADS*" "*METAL*" "*MODEL*" "*TOP-K*" "*TFS-Z*" "*TOP-P*" "*TYPICAL-P*" "*TEMP*"
	   "*MIROSTAT*" "*MIROSTAT-ETA*" "*MIROSTAT-TAU*" "*REPEAT-PENALTY*"
	   "*REPEAT-LAST-N*" "*PRESENCE-PENALTY*" "*FREQUENCY-PENALTY*" "*PENALIZE-NEWLINES*"
	   ;;
	   "SYSTEM-INFO" "MAX-DEVICES" "MMAP-SUPPORTED" "MLOCK-SUPPORTED" "GPU-OFFLOAD-SUPPORTED"
	   "PARAMS" "N-CTX" "N-CTX-TRAIN" "N-BATCH" "N-UBATCH" "N-SEQ-MAX" "POOLING-TYPE"
	   "VOCAB-TYPE" "ROPE-TYPE" "N-VOCAB" "N-EMBD" "N-LAYER" "DESC" "SIZE" "N-PARAMS"
	   "TOKEN" "TOKEN-EOS" "TOKEN-NL" "TOKEN-CLS" "TOKEN-SEP" "TOKEN-PREFIX" "TOKEN-MIDDLE" "TOKEN-SUFFIX" "TOKEN-EOT"
	   "GET-TOKEN" "PRINT-TIMINGS" "RESET-TIMINGS" "TOKENS" "LIST-TOKENS" "CTX" "MDL" "CHAIN"
	   "TOKENIZE" "EVALUATE" "GET-EMBEDDINGS" "GET-LOGITS" "SAMPLE-TOP-P-TOP-K" "GET-VOCAB"
	   ;;
	   "ALLOCATE-CANDIDATES" "ALLOCATE-CANDIDATES-P" "INIT-CANDIDATES"
	   ;; 
	   "SIMPLE" "EMBEDDING" "PERPLEXITY" "LLAMA"))

(defpackage #:llama.test
  (:use #:cl #:llama)
  (:export "RUN"))
